In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('covid_toy.csv')

In [3]:
df.sample(10)

    age  gender  fever   cough       city has_covid
44   20    Male  102.0  Strong      Delhi        No
11   65  Female   98.0    Mild     Mumbai       Yes
7    20  Female    NaN  Strong     Mumbai       Yes
49   44    Male  104.0    Mild     Mumbai        No
38   49  Female  101.0    Mild      Delhi       Yes
17   40  Female   98.0  Strong      Delhi        No
96   51  Female  101.0  Strong    Kolkata       Yes
58   23    Male   98.0  Strong     Mumbai       Yes
5    84  Female    NaN    Mild  Bangalore       Yes
35   82  Female  102.0  Strong  Bangalore        No

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df["has_covid"],test_size=0.2)

In [5]:
X_train

    age  gender  fever   cough       city
44   20    Male  102.0  Strong      Delhi
51   11  Female  100.0  Strong    Kolkata
85   16  Female  103.0    Mild  Bangalore
88    5  Female  100.0    Mild    Kolkata
25   23    Male    NaN    Mild     Mumbai
..  ...     ...    ...     ...        ...
11   65  Female   98.0    Mild     Mumbai
98    5  Female   98.0  Strong     Mumbai
40   49  Female  102.0    Mild      Delhi
66   51    Male  104.0    Mild    Kolkata
56   71    Male    NaN  Strong    Kolkata

[80 rows x 5 columns]

In [6]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

X_test_fever=si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [32]:
X_train

    age  gender  fever  cough       city
44   20    Male  102.0      1      Delhi
51   11  Female  100.0      1    Kolkata
85   16  Female  103.0      0  Bangalore
88    5  Female  100.0      0    Kolkata
25   23    Male    NaN      0     Mumbai
..  ...     ...    ...    ...        ...
11   65  Female   98.0      0     Mumbai
98    5  Female   98.0      1     Mumbai
40   49  Female  102.0      0      Delhi
66   51    Male  104.0      0    Kolkata
56   71    Male    NaN      1    Kolkata

[80 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import ColumnTransformer
Transformer=ColumnTransformer(Transformer=[],remainder='passthrough')